# Generated by Django 4.2.13 on 2024-08-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_book_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
